name: notes_app
description: A beautiful notes application with calendar integration
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2
  path: ^1.8.3
  intl: ^0.18.1
  provider: ^6.0.5
  google_fonts: ^5.1.0
  flutter_staggered_grid_view: ^0.7.0
  table_calendar: ^3.0.9
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
